// Mocks generated by Mockito 5.0.15 from annotations
// in mais_filmes/test/app/modules/login/data/repositories/login_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mais_filmes/app/modules/login/data/sources/login_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ILoginDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoginDataSource extends _i1.Mock implements _i2.ILoginDataSource {
  MockILoginDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> login(String? email, String? name) =>
      (super.noSuchMethod(Invocation.method(#login, [email, name]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> signup(String? email, String? name) =>
      (super.noSuchMethod(Invocation.method(#signup, [email, name]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  String toString() => super.toString();
}
