// Mocks generated by Mockito 5.0.15 from annotations
// in mais_filmes/test/app/modules/home/data/repositories/movies_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mais_filmes/app/modules/home/data/sources/movies_data_source.dart'
    as _i2;
import 'package:mais_filmes/app/shared/network/interfaces/connectivity_interface.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IMoviesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMoviesDataSource extends _i1.Mock implements _i2.IMoviesDataSource {
  MockIMoviesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> popular(int? page) =>
      (super.noSuchMethod(Invocation.method(#popular, [page]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<List<Map<String, dynamic>>> favorites(int? userId) =>
      (super.noSuchMethod(Invocation.method(#favorites, [userId]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<void> addFavorite(Map<String, dynamic>? movieData) =>
      (super.noSuchMethod(Invocation.method(#addFavorite, [movieData]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> removeFavorite(int? id, int? userId) =>
      (super.noSuchMethod(Invocation.method(#removeFavorite, [id, userId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<Map<String, dynamic>> getMovieDetails(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetails, [id]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [IConnectivityDriver].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConnectivityDriver extends _i1.Mock
    implements _i4.IConnectivityDriver {
  MockIConnectivityDriver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  String toString() => super.toString();
}
